### ISSUE TITLE
Organize directories

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#10]
Organize file structure. For example, move assets folders from the root directory to _assets/ kinda like https://github.com/arkon/arkon.github.io/tree/draft.

**Comment by tejasmanohar** [comment]
fonts, img, etc. should be in __assets/ as well logically

+ follow naming convention for directories
>Pipeline assets should be under your sources directory of Jekyll site. When a file is referenced with liquid tag or with helper from another asset, Sprockets searches the three default asset locations for it: _assets/images, _assets/javascripts and _assets/stylesheets.

from https://github.com/jekyll-assets/jekyll-assets

**Comment by tejasmanohar** [comment]
`fonts/` should also be in `_assets/`

look here -> https://github.com/jekyll-assets/jekyll-assets/issues/50

**Comment by mazlix** [comment]
Hey, if I put fonts under _assets then we need to use scss rather than css (to get the assets path), but if we use scss, the uncss (css cleaner) will convert it to css so we won't get the path to font file. 

Options I can think of:

1. Run css cleaner after jekyll build 
2. No longer run css cleaner on (s)css stylesheet with font paths in them (I've already run it initally once) [that would mean `uncss` would not run on `font-awesome.min.css`.. which should be fine]

**Comment by mazlix** [comment]
Nevermind! It works as a .css file!

**Comment by tejasmanohar** [comment]
@mazlix which method did you take to resolve this in #19?

**Comment by tejasmanohar** [comment]
@mazlix which method did you take to resolve this in #19?

**Comment by mazlix** [comment]
Option 2).. fonts are now under _assets/fonts, the `fontawesome.min` file got changed to a `scss` file, and the `uncss` command reads it and exports it as scss so it works fine.
