### ISSUE TITLE
safe concurrency level?

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#33]
what's the current default s3 concurrency level at? what is a safe # for this statistic? what all does it affect? does this affect people viewing the site or just those working w/ S3 filesystem directly, like pushing / pulling / modifying permissions etc?

**Comment by mazlix** [comment]
Yeah it's just those working with the S3 filesystem. How many concurrent uploads do you allow to S3. A higher number (default is at 3) could make uploading the site faster. But if you put it too high issues can happen. Since the site is pretty small I think you're good to with 3. It uploads pretty quick already.

(https://github.com/laurilehmijoki/s3_website#specifying-custom-concurrency-level)
